version: "3.7"
services:
  web:
    build: .
    depends_on:
      - redis
    restart: always
    volumes:
      - ./srv/log:/app/log
    ports:
      - "8080:8080"
    environment:
      - FG_REDIS_HOST=redis:6379
      - FG_REDIS_PASSWORD=
      - FG_REDIS_DB=0
  redis:
    image: redis:5
    volumes:
      - ./srv/redis:/data
    expose:
      - "6379"
